### ISSUE TITLE
When updating from 13.2.0 to 13.2.1 with local node, the entire blockchain is wiped away and wallet settings gone

### ISSUE THREAD

**Issue by gab81** [EquilibriaCC/equilibria-wallet-outdated#7]
hello,

i have just installed the latest GUI 13.2.1 / win10 with the new exe provided and i have to point out one more major issue we have again.

I had my GUI 13.2.0 up and running with the local database, which takes 24 hours to sync. Fine.

With the previous releases, the ones H would send out, when you update normally you wouldn't lose the whole blockchain.

Now, i have just installed the 13.2.1 and once again, like when i installed 13.2.0 last week, my entire blockchain is gone, as well as all the wallet settings, which isn't great, i think there's still room for improvement. So now back to using the seed phrase again (not a huge deal but annoying) and i need to re-sync again and it will take again 24 hours.

I think this should also be addressed. thank you.

**Comment by AdminXeq** [comment]
Do You use standard directory path for blockchain storage. You can choose manually directory where you store blockchain and wallet. Update change config file to default values.

**Comment by gab81** [comment]
No, i have custom config on external SSD which perfectly works after sync is completed and takes 24 hours. Not using standard drive C.

Got the new .exe, install and it should automatically get all values currently used and maintain that way - what it did, erased completely the blockchain and wallet settings on my external SSD.

Are you suggesting, first install, then it will default to C, then close then open config then change to whatever letter and that way it will "keep" the downloaded blockchain?

**Comment by AdminXeq** [comment]
In "Daemon settings" under advanced options 
Data storage path
Wallet storage path
Use your own directory, there is no reason to delete blockchain and sync again
After adjust data directories restart GUI

**Comment by gab81** [comment]
hi,

i am sorry you do not get it what the issue is, let me repeat:

Last week i installed 13.2.0, of course i updated data dir and all that, i am using these softwares from a while. It fully synced, i have ran it a few times afterwards, on and off, but the disappearing transactions issue.... moving on....

NOW, last night i downloaded and installed 13.2.1 with the installer, so what you normally do, you run the .exe without deleting previous version and it takes the settings, right?

no, now it does NOT recognise the settings, and it wipes out the entire blockchain which i set on a customised external drive and now i have to sync again, 24 hours again.

The expected behaviour is that when you have an updated release, then the program recognises if you have already the data folder with the entire blockchain and not wiping it out entirely and starting from scratch again. XEQ is not too big so 24 hours isn't a huge deal, if this was BTC it takes me 1 week to sync :-(

Or perhaps i am doing the wrong steps when updating? i.e. during setup do you need to set the standard C:\ data dir, then launch it once, then edit config.json? or do i need to backup the datadir first elsewhere then instal then copy and paste?

hope this helps you addressing the issue. thank you

**Comment by AdminXeq** [comment]
In this place C:\ProgramData\equilibria\gui adjust config.json in section

"app": {
        "data_dir": "C:\\equilibria",
        "wallet_data_dir": "C:\\Users\\USER\\Documents\\equilibria",
        "ws_bind_port": 10231,
        "net_type": "mainnet",
        "scan": false

data_dir -> where You have blockchain 
Than it start to work for me with different bc location, also did not remove the current base.
Configuration is always stored in C:\ProgramData\equilibria\gui

**Comment by gab81** [comment]
Yes! but is that before or after when you do an upgrade?

There should be a how-to when you're already set up and just upgrading, for new installs, that's fine. It's two different things.

I had everything up and set up properly, then launched the new 13.2.1 and then that wiped everything out.

Like for example now, it's re-downloading the whole blockchain, it will complete this evening - fine.

What about next time when you release 14.0 ? how am i going to upgrade again this time so i don't lose all the blockchain again?

thank you

**Comment by gab81** [comment]
hello, just as an update, everything works well with 13.2.1 - finished sync. For some odd reason i didn't have my wallet balance correct, i just did a delete wallet then restored from seed and everything is good now.

Staking pools tab is populated and so are receiving addresses.

Also, i have ran monero core at the same time and it seems as though they peacefully coexist now (you couldn't launch both a few releases back) although i haven't done any new transaction yet.

Hopefully at next equi wallet update it's smoother and won't lose again the blockchain.

thanks a lot and keep up the hard work!

**Comment by muscleman** [comment]
believe your issue is the new electron wallet installation is overwriting your old electron wallet configuration.
so when you run the electron wallet again, it doesn't know the location of your existing block chain [usb drive] and starts to download again
NOT that the electron wallet is deleting your block chain.

just my two cents.
